# Generated by Django 5.0 on 2023-12-21 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalIndicators",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pulse", models.IntegerField()),
                ("steps", models.IntegerField()),
                ("distance", models.IntegerField()),
                (
                    "bodybuilder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.bodybuilder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FitnessBracelet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "physical_indicators",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.physicalindicators",
                    ),
                ),
            ],
        ),
    ]
