# Generated by Django 4.2.8 on 2023-12-23 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_fitnessbracelet_id_alter_physicalindicators_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalindicators",
            name="sleep_hours",
            field=models.DurationField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
