# Generated by Django 4.2.8 on 2023-12-23 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_physicalindicators_sleep_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="physicalindicators",
            name="sleep_hours",
        ),
    ]
