# Generated by Django 4.2.8 on 2023-12-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_remove_physicalindicators_sleep_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodybuilder",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
