# Generated by Django 5.0 on 2024-01-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_bodybuilder_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bodybuilder",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
